In [6]:
import numpy as np 
import tensorflow as tf
t0 = tf.constant(1)
print(t0)
print(tf.rank(t0))

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(0, shape=(), dtype=int32)


In [7]:
t1 = tf.constant([1,2,3])
print(t1)
print(tf.rank(t1))

tf.Tensor([1 2 3], shape=(3,), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)


In [8]:
t2 = tf.constant([[1,2,3,],
                  [4,5,6],
                  [7,8,9]])
print(t2)
print(tf.rank(t2))

tf.Tensor(
[[1 2 3]
 [1 2 3]
 [1 2 3]], shape=(3, 3), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)


In [9]:
t3 = tf.constant([[[1,2,3],[4,5,6],[7,8,9]],
                 [[1,2,3],[4,5,6],[7,8,9]],
                 [[1,2,3],[4,5,6],[7,8,9]]])
print(t3)
print(tf.rank(t3))

tf.Tensor(
[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]], shape=(3, 3, 3), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)


In [11]:
t4 = tf.constant([[[[1,2,3],[4,5,6],[7,8,9]],
                 [[1,2,3],[4,5,6],[7,8,9]],
                 [[1,2,3],[4,5,6],[7,8,9]]],
                  
                 [[[1,2,3],[4,5,6],[7,8,9]],
                 [[1,2,3],[4,5,6],[7,8,9]],
                 [[1,2,3],[4,5,6],[7,8,9]]],
                 
                 [[[1,2,3],[4,5,6],[7,8,9]],
                 [[1,2,3],[4,5,6],[7,8,9]],
                 [[1,2,3],[4,5,6],[7,8,9]]]])
print(t4)
print(tf.rank(t4))

tf.Tensor(
[[[[1 2 3]
   [4 5 6]
   [7 8 9]]

  [[1 2 3]
   [4 5 6]
   [7 8 9]]

  [[1 2 3]
   [4 5 6]
   [7 8 9]]]


 [[[1 2 3]
   [4 5 6]
   [7 8 9]]

  [[1 2 3]
   [4 5 6]
   [7 8 9]]

  [[1 2 3]
   [4 5 6]
   [7 8 9]]]


 [[[1 2 3]
   [4 5 6]
   [7 8 9]]

  [[1 2 3]
   [4 5 6]
   [7 8 9]]

  [[1 2 3]
   [4 5 6]
   [7 8 9]]]], shape=(3, 3, 3, 3), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)


In [18]:
i = tf.constant(2)
print(i)
f = tf.constant(2.)
print(f)
s = tf.constant('hdh')
print(s)
f16 = tf.constant(2.,dtype=tf.float16)
print(f16)
i8 = tf.constant(2, dtype=tf.int8)
print(i8)
f32 = tf.cast(f16, tf.float32)
print(f32)
i32 = tf.cast(i8, tf.int32)
print(i32)

tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(2.0, shape=(), dtype=float32)
tf.Tensor(b'hdh', shape=(), dtype=string)
tf.Tensor(2.0, shape=(), dtype=float16)
tf.Tensor(2, shape=(), dtype=int8)
tf.Tensor(2.0, shape=(), dtype=float32)
tf.Tensor(2, shape=(), dtype=int32)


In [35]:
from tensorflow.python.keras.layers import Dense,Activation,Flatten,Input
from tensorflow.python.keras.models import Model
from tensorflow.python.keras.layers import Concatenate
input_layer = Input(shape= (23,23))
hidden1 = Dense(100, activation= 'relu')(input_layer)
hidden2 = Dense(50, activation='relu')(hidden1)
hidden3 = Dense(30, activation='relu')(hidden2)
concat = Concatenate()([input_layer, hidden3])
output = Dense(1)(concat)
model = Model(inputs = [input_layer], outputs = [output])
model.summary()

Model: "model"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_1 (InputLayer)            [(None, 23, 23)]     0                                            
__________________________________________________________________________________________________
dense_1 (Dense)                 (None, 23, 100)      2400        input_1[0][0]                    
__________________________________________________________________________________________________
dense_2 (Dense)                 (None, 23, 50)       5050        dense_1[0][0]                    
__________________________________________________________________________________________________
dense_3 (Dense)                 (None, 23, 30)       1530        dense_2[0][0]                    
______________________________________________________________________________________________